// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://enbeskgwaoyrwvsrdipi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVuYmVza2d3YW95cnd2c3JkaXBpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNTM2MTIsImV4cCI6MjA1ODgyOTYxMn0.HaEt2MN2hoYA9Ss-8HKjlyfC6VWwNPqivad1DrdkM0k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);